const convertMarkdownToHTML = (text: string): string => {
  const escaped = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  return escaped
    .replace(/^## (.*)/gm, '<h2>$1</h2>')
    .replace(/^### (.*)/gm, '<h3>$1</h3>')
    .replace(/^# (.*)/gm, '<h1>$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/^/, '<p>')
    .replace(/$/, '</p>');
};

export const generateReportPDF = async (reportText: string, childName: string): Promise<void> => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Popup blocked — allow popups to print the report.');
  }

  const formattedHTML = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${childName} — Child Destiny Report</title>
      <style>
        body { 
          font-family: Georgia, serif; 
          max-width: 800px; 
          margin: 0 auto; 
          padding: 40px;
          line-height: 1.8;
          color: #1a1a2e;
        }
        h1 { color: #1F3A5F; font-size: 28px; }
        h2 { color: #1F3A5F; font-size: 22px; 
             border-bottom: 2px solid #c9a96e;
             padding-bottom: 8px; margin-top: 40px; }
        h3 { color: #2E75B6; font-size: 18px; }
        .cover { 
          text-align: center; 
          padding: 120px 0;
          page-break-after: always;
        }
        .cover-title { 
          font-size: 42px; 
          color: #1F3A5F; 
          font-weight: bold; 
        }
        .cover-sub { 
          font-size: 24px; 
          color: #c9a96e;
          margin-top: 20px; 
        }
        .section { page-break-before: always; }
        p { margin-bottom: 16px; }
        .footer { 
          text-align: center; 
          color: #666; 
          font-size: 12px;
          margin-top: 60px;
          border-top: 1px solid #ddd;
          padding-top: 20px;
        }
        @media print {
          body { margin: 0; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="cover">
        <div class="cover-title">AATMABODHA</div>
        <div class="cover-sub">Child Destiny Report</div>
        <div style="margin-top: 60px; font-size: 32px; 
                    color: #1F3A5F; font-weight: bold;">
          ${childName.replace(/</g, '')}
        </div>
        <div style="margin-top: 20px; color: #666; font-size: 16px;">
          What this child is built for — and how to raise them into it
        </div>
        <div style="margin-top: 40px; color: #666; font-size: 14px;">
          Generated by Aatmabodha · ${new Date().toLocaleDateString('en-IN', {
            day: 'numeric',
            month: 'long',
            year: 'numeric',
          })}
        </div>
      </div>
      
      ${convertMarkdownToHTML(reportText)}
      
      <div class="footer">
        <p>This report was generated by Aatmabodha — AI-Native Vedic Oracle</p>
        <p>Prepared with love for ${childName.replace(/</g, '')}'s parents</p>
        <p>aatmabodha1.onrender.com</p>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(formattedHTML);
  printWindow.document.close();

  window.setTimeout(() => {
    printWindow.print();
  }, 1000);
};
